version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/quizdb
      - NODE_ENV=production
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - quiz-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/api/quizzes"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quizdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - quiz-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  quiz-network:
    driver: bridge

volumes:
  postgres-data:
    # Adding a name makes it easier to identify the volume
    name: quiz-master-postgres-data