server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.org/mergeable-ingress-type: "master"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      cert-manager.io/cluster-issuer: "http01-prod"
    hosts:
      - host: gitops.drintech.online
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - gitops.drintech.online
        secretName: argocd-server-tls
  extraArgs:
    - --insecure

global:
  domain: test.drintech.online