apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: http01-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: drintech222@gmail.com
    privateKeySecretRef:
      name: http01-prod
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx